// Copyright 2026 Evgeny Kapusta (@ryodeushii)
// SPDX-License-Identifier: GPL-2.0-or-later

#undef RGB_MATRIX_DEFAULT_MODE
#undef RGB_DEFAULT_COLOR
#undef RGB_MATRIX_DEFAULT_SAT
#undef RGB_MATRIX_DEFAULT_VAL
#undef DEFAULT_RGB_MATRIX_BRIGHTNESS
#undef DEFAULT_USB_SLEEP_TOGGLE
#undef DEFAULT_CAPS_INDICATOR_TYPE
#undef DEFAULT_SIDE_BRIGHTNESS
#undef DEFAULT_SIDE_MODE_A
#undef DEFAULT_SIDE_STATIC_HUE
#undef DEFAULT_SIDE_STATIC_SAT
#undef DEBOUNCE
#undef RELEASE_DEBOUNCE

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_DEFAULT_COLOR 190
#define RGB_MATRIX_DEFAULT_SAT 247
#define DEFAULT_RGB_MATRIX_BRIGHTNESS (RGB_MATRIX_MAXIMUM_BRIGHTNESS - RGB_MATRIX_VAL_STEP)
#define RGB_MATRIX_DEFAULT_VAL DEFAULT_RGB_MATRIX_BRIGHTNESS

#define DEFAULT_USB_SLEEP_TOGGLE true
#define DEFAULT_CAPS_INDICATOR_TYPE CAPS_INDICATOR_BOTH

#define DEFAULT_SIDE_BRIGHTNESS 5
#define DEFAULT_SIDE_MODE_A 4
#define DEFAULT_SIDE_STATIC_HUE 190
#define DEFAULT_SIDE_STATIC_SAT 247

#define DEBOUNCE 5
#define RELEASE_DEBOUNCE 10
