#pragma once

#define NUPHY_VIA_EEPROM_CUSTOM_CONFIG_SIZE 23

#ifndef VIA_ENABLE
#    ifndef EECONFIG_KB_DATA_SIZE
#        define EECONFIG_KB_DATA_SIZE NUPHY_VIA_EEPROM_CUSTOM_CONFIG_SIZE
#    endif
#endif

#define VIA_EEPROM_CUSTOM_CONFIG_SIZE NUPHY_VIA_EEPROM_CUSTOM_CONFIG_SIZE
