// Copyright 2024 Evgeny Kapusta (@ryodeushii)
// SPDX-License-Identifier: GPL-2.0-or-later

#undef RGB_MATRIX_DEFAULT_MODE
#undef RGB_DEFAULT_COLOR
#undef DEFAULT_SIDE_MODE_A
#undef DEFAULT_SIDE_MODE_B
#undef DEFAULT_SIDE_COLOR
#undef DEFAULT_SIDE_BRIGHTNESS
#undef DEFAULT_CAPS_INDICATOR_TYPE
#undef DEFAULT_LIGHT_CUSTOM_KEYS
#undef DEFAULT_SLEEP_TIMEOUT
#undef DEFAULT_BATTERY_INDICATOR_NUMERIC
#undef DEFAULT_DETECT_NUMLOCK
#undef DEFAULT_USB_SLEEP_TOGGLE

#define DEFAULT_RGB_MATRIX_BRIGHTNESS (RGB_MATRIX_VAL_STEP * 2)
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_DEFAULT_COLOR 190
#define DEFAULT_SIDE_MODE_A 2
#define DEFAULT_SIDE_MODE_B 1
#define DEFAULT_SIDE_COLOR 6
#define DEFAULT_SIDE_BRIGHTNESS 4

#define DEFAULT_BATTERY_INDICATOR_NUMERIC 1
#define DEFAULT_CAPS_INDICATOR_TYPE CAPS_INDICATOR_BOTH
#define DEFAULT_LIGHT_CUSTOM_KEYS 1
#define DEFAULT_USB_SLEEP_TOGGLE true
#define DEFAULT_SLEEP_TIMEOUT 5
#define DEFAULT_DETECT_NUMLOCK 0
#define DEBUG_MATRIX_SCAN_RATE 1
