// Copyright 2024 Evgeny Kapusta (@ryodeushii)
// SPDX-License-Identifier: GPL-2.0-or-later

#undef DEFAULT_RGB_MATRIX_BRIGHTNESS
#undef RGB_MATRIX_DEFAULT_MODE
#undef RGB_DEFAULT_COLOR
#undef DEFAULT_SIDE_MODE
#undef DEFAULT_SIDE_COLOR
#undef DEFAULT_SIDE_BRIGHTNESS
#undef DEFAULT_AMBIENT_MODE
#undef DEFAULT_AMBIENT_COLOR
#undef DEFAULT_AMBIENT_BRIGHTNESS
#undef DEFAULT_CAPS_INDICATOR_TYPE
#undef DEFAULT_LIGHT_CUSTOM_KEYS
#undef DEFAULT_SLEEP_TIMEOUT
#undef DEFAULT_BATTERY_INDICATOR_NUMERIC
#undef DEFAULT_DETECT_NUMLOCK
#undef DEFAULT_SIDE_USE_CUSTOM_COLOR
#undef DEFAULT_AMBIENT_USE_CUSTOM_COLOR
#undef DEFAULT_SHOW_SOCD_INDICATOR
#undef DEFAULT_USB_SLEEP_TOGGLE

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_DEFAULT_COLOR 15
#define DEFAULT_SIDE_MODE 2
#define DEFAULT_SIDE_COLOR 1
#define DEFAULT_SIDE_BRIGHTNESS 3
#define DEFAULT_AMBIENT_MODE 2
#define DEFAULT_AMBIENT_COLOR 1
#define DEFAULT_AMBIENT_BRIGHTNESS 3

#define DEFAULT_RGB_MATRIX_BRIGHTNESS (RGB_MATRIX_VAL_STEP * 2)

#define DEFAULT_BATTERY_INDICATOR_NUMERIC 1
#define DEFAULT_CAPS_INDICATOR_TYPE CAPS_INDICATOR_BOTH
#define DEFAULT_LIGHT_CUSTOM_KEYS 1
#define DEFAULT_USB_SLEEP_TOGGLE true
#define DEFAULT_SLEEP_TIMEOUT 5
#define DEFAULT_DETECT_NUMLOCK 0
#define DEFAULT_SIDE_USE_CUSTOM_COLOR 1
#define DEFAULT_AMBIENT_USE_CUSTOM_COLOR 1
#define DEFAULT_SHOW_SOCD_INDICATOR 1

#define DEBUG_MATRIX_SCAN_RATE 1
