#undef CUSTOM_KEYS_HIGHLIGHT_ENABLED
#define CUSTOM_KEYS_HIGHLIGHT_ENABLED false

#undef NUPHY_SIDE_LIGHTING_ENABLED
#define NUPHY_SIDE_LIGHTING_ENABLED 0

#undef NUPHY_AMBIENT_LIGHTING_ENABLED
#define NUPHY_AMBIENT_LIGHTING_ENABLED 0

#undef RGB_MATRIX_LED_COUNT
#define RGB_MATRIX_LED_COUNT 128

#define CAPS_LOCK_INDEX 46

#undef RGB_MATRIX_DEFAULT_MODE
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
