name: Build Nuphy Keyboards

permissions:
  contents: read

on:
  push:
    tags:
      - 'r*.*.*'
      - 'r*-pre'

concurrency: ci_build-${{ github.ref_name }}

jobs:
  ci_builds:
    name: Build
    timeout-minutes: 1380
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container: ghcr.io/qmk/qmk_cli

    steps:
    - name: Disable safe.directory check
      run : git config --global --add safe.directory '*'

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Run `./compile_halo.sh`
      run: |
        chmod +x compile_all.sh
        ./compile_all.sh ${{ github.ref_name }}

        [ ! -f .failed ] || exit 1

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{  github.ref_name }}-artifacts
        if-no-files-found: ignore
        path: |
          *.bin

    - name: Create draft release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags')
      with:
        files: |
          *.bin
          !*-ryodeushii-*.bin
          keyboards/nuphy/halo75v2/*/keymaps/via/*via3.json
          keyboards/nuphy/air75v2/*/keymaps/via/*via3.json
          keyboards/nuphy/gem80/*/keymaps/via/*via3.json
        tag_name: ${{ github.ref_name }}
        draft: true
        prerelease: true
        token: ${{ secrets.CUSTOM_TOKEN }}
